# Basic Information 
title: Daksh Shah
position: Computer Science M.S. Student
affiliation: New York University (Courant Institute) 
email: daksh.shah (at) nyu.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: 3D reconstruction, computer vision, machine learning, neural attenuation fields, neural radiance fields, 3D gaussian splatting, 3DGS, medical imaging, 3D computer vision
description: Computer Vision Researcher and Computer Science MS Student at NYU. 
canonical: https://dakshshah.com/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=NIRVR40AAAAJ&hl=en
cv_link: ./assets/files/curriculum_vitae.pdf
github_link: https://github.com/dakshshah03
linkedin: https://www.linkedin.com/in/dakshkshah
twitter: https://x.com/torchedvision

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/pfp/IMG_3888_pfp_square.JPG
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: G-5GTCRW37N2

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
